year: 2024
description: 'yest and USP2 proteins spiked in different concentration. Experiment is designed for DIA benchmarking of different workflow using DIA-NN.'
input_file: 'data/report.tsv'
design_file: 'data/annotation_DIA_dummy.csv'
formula: ''
contrast: 'Group'
comparisons: ['GroupB - GroupA','GroupC - GroupA']