title: 'DIA Benchmark Experiment'
subtitle: 'DE Analysis'
author: 'Andrea' 
description: 'Yeast as background and USP2 proteins spiked in different concentration. This Experiment is designed for DIA benchmarking of different workflow using DIA-NN.'
input_file: 'data/report.tsv'
design_file: 'data/annotation_DIA_dummy.csv'
formula: ''
contrast: 'Group'
aggr_method: 'robustSummary' # medianPolish robustSummary() ; base::colMeans() matrixStats::colMedians() base::colSums()
normalization: 'quantiles' # "sum", "max", "center.mean", "center.median", "div.mean", "div.median", "diff.meda", ⁠"quantiles⁠", ⁠"quantiles.robust⁠" or "vsn"
# include only proteotypic peptides
Proteotypic: TRUE
# number of peptide per proteins
pep_per_prot: 3
#number of samples per peptides  with non missing value > 
nNonZero: 3
comparisons: ['GroupB - GroupA','GroupD - GroupA']

# ['GroupB - GroupA', 'GroupC - GroupA']